// LOGIN 
POST http://request-ticket-digistar-api.vercel.app/login
Content-Type: application/json

{
    "email": "supportadmin@gmail.com",
    "password": "adminpw"
}

###
// LOGOUT
DELETE http://request-ticket-digistar-api.vercel.app/logout

### 
// GET SELF INFO
GET http://request-ticket-digistar-api.vercel.app/me
