// LOGIN 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "supportadmin@gmail.com",
    "password": "adminpw"
}

###
// LOGOUT
DELETE http://localhost:3000/logout

### 
// GET SELF INFO
GET http://localhost:3000/me
