### GET TICKETS
GET http://localhost:5000/tickets

### DOWNLOAD TICKET'S ATTACHMENT BY TICKET'S UUID
GET http://localhost:5000/tickets_download/011f1380-b025-4adf-a867-4ff97b6c36cf

// di menu "Board", untuk filter ticket berdasarkan status 'to do', 'on-process', dan 'done' dari Frontend aja ya
// di menu "Board", untuk adjust data ticket apa aja yg ditampilin juga sesuai di FE aja
// di menu "Calendar" dan "Timeline" juga tampilin sesuai 'start_date' dan 'due_date' dari ticket