// Create User (saran, di postman aja biar lebih gampang upload profile picture)
POST http://request-ticket-digistar-api.vercel.app/users
Content-Type: multipart/form-data

# name : text
# email : text
# password : text
# confPassword : text
# role (admin, user, manager, teknis) : text
# nomor_handphone : text
# profile_picture : file  |  profile_picture bisa null (tidak diisi)

###
// SHOW ALL USERS | return profile_picture dalam format base64
GET http://request-ticket-digistar-api.vercel.app/users

###
// GET ONE SPECIFIC USER BY UUID (JUST IN-CASE IF NEEDED)
GET http://request-ticket-digistar-api.vercel.app/users/cafd7488-0a16-4c30-b90b-e386ba26938d

###
// DELETE USER BY UUID
DELETE http://request-ticket-digistar-api.vercel.app/users/1

###
// UPDATE/PATCH USER BY UUID   !! ROLE GABOLEH DI UPDATE !! (saran, di postman aja biar lebihh gampang)
PATCH http://request-ticket-digistar-api.vercel.app/users/b6a7c382-039d-455c-881f-1bb684d8ff80
Content-Type: multipart/form-data

# name : text
# email : text
# password : text
# confPassword : text
# nomor_handphone : text
# profile_picture : file 

### create user tanpa nambah profile picture
POST http://request-ticket-digistar-api.vercel.app/users
Content-Type: application/json

{
    "name": "Non Teknis",
    "email": "nonteknis@gmail.com",
    "password": "nonteknis",
    "confPassword": "nonteknis",
    "role": "user",
    "nomor_handphone": "0891234567890"
}