### GET TICKETS : untuk filter dan sort disesuaikan sama UI aja ya, termasuk data ticket yg ditampilkan disesuaikan aja sama UI
GET http://localhost:5000/tickets

### ASSIGN TICKET TO ROLE TEKNIS AND OR APPROVE/DECLINE DI BAGIAN STATUS
PATCH http://localhost:5000/tickets/6e89d3c2-e70e-4d24-b185-eaad5610eecd
Content-Type: application/json

{
    "assigned_tech": "11", 
    "status": "to do" 
}
// value `assigned_tech` berupa id dari user role teknis jika mau assign ticket
// status: jika klik 'X' maka update status = decline. jika 'V' maka update status = to do

### GET USERS BY ROLE "teknis"
GET http://localhost:5000/users/teknis

### GET ATTACHMENT (TICKET RESPONSE) BY TICKET ID: ditampilkan ketika logo attachment di klik, ketika status ticket = done
GET http://localhost:5000/tickets/6/responses

### DOWNLOAD ATTACHMENT FILE BY TICKET RESPONSE UUID : ketika ticket response ditampilkan di pop-up
GET http://localhost:5000/attachments/4e240806-eaf6-439e-af64-037f07d3f601