// CREATE PRODUCT/PROJECT | saran, di postman aja biar lebih gampang
POST http://localhost:5000/productprojects
Content-Type: multipart/form-data

# issue_type ('product' / 'project') : text
# name : text
# description : text
# pic (id user role manager) : text
# profile_picture : file (image, opsional)

###
// UPDATE PRODUCT/PROJECT | saran, di postman aja biar lebih gampang
PATCH http://localhost:5000/productprojects/8b90743d-19c0-44ff-b7bc-f00b7ff8b334
Content-Type: multipart/form-data

# issue_type ('product' / 'project') : text
# name : text
# description : text
# pic (id user role manager) : text
# profile_picture : file (image, opsional)

### 
// GET (SHOW) ALL PRODUCT/PROJECT
GET http://localhost:5000/productprojects

###
// GET (SHOW) SPECIFIC PRODUCT/PROJECT
GET http://localhost:5000/productprojects/a3c4f6ee-380f-4fcb-b906-da5c3a6b47ce

###
// DELETE A PRODUCT/PROJECT
DELETE http://localhost:5000/productprojects/6233571b-fff5-4693-a43e-aa54137774ad
